name: GitHub CI .Net 4.8

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: windows-latest
       
    steps:   
    - uses: actions/checkout@v2

    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
  
    - uses: nuget/setup-nuget@v1
    - run: nuget restore Netch.sln
     
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build .NET 4.8 Netch
      shell: pwsh
      run: |
        .\build.ps1
        
    - name: Upload Netch.x64
      uses: actions/upload-artifact@v1
      with:
        name: Netch.X64
        path: Netch\bin\x64\Release\win-x64
        
    - name: Upload Netch.x86
      uses: actions/upload-artifact@v1
      with:
        name: Netch.X86
        path: Netch\bin\x86\Release\win-x86

    - name: Release
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "true"
        CHANGELOG_FILE: "CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "true"
        ALLOW_TAG_PREFIX: "true"
        RELEASE_NAME_POSTFIX: " (nightly build)"
      with:
        args: |
            Netch.X64.zip
            Netch.X86.zip
